<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.8" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.8" /> <!-- Link 3 -->
  <xacro:property name="height4" value="0.8" /> <!-- Link 4 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/rrbot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
	<limit effort="1000" velocity="2.0" lower="${-PI*1.25}" upper="${+PI*1.25}" />
    <dynamics damping="10"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link4"/>
    <origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="10"/>
  </joint>

  <!-- Middle Link 2 -->
  <link name="link4">
    <collision>
      <origin xyz="0 0 ${height4/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height4}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height4/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height4}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height4/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint3" type="continuous">
    <parent link="link4"/>
    <child link="link3"/>
    <origin xyz="0 ${width} ${height4 - axel_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="10"/>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="gripper_palm_joint" type="fixed">
    <axis xyz="0 1 0"/>
    <origin rpy="0 0 0" xyz="0 0 0.475"/>
    <parent link="link3"/>
    <child link="palm"/>
  </joint>

  <link name="palm">
    <collision>
      <origin xyz="0.0 0.0 0.3" rpy="0 0 0"/>
      <geometry>
		<box size="0.1 0.4 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.0 0.0 0.3" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.4 0.1"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0.0 0.0 0.2" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="gripper_left_finger_joint" type="prismatic">
    <axis xyz="0 1 0"/>
    <origin rpy="0 0 0" xyz="0 0 0.475"/>
    <limit effort="1000.0" lower="-0.2" upper="0" velocity="0.5"/>
    <parent link="palm"/>
    <child link="left_finger"/>
    <dynamics damping="10"/>
  </joint>

  <link name="left_finger">
    <collision>
      <origin xyz="0.0 0.2 0.1" rpy="0 0 0"/>
      <geometry>
		<box size="0.1 0.1 0.4"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.0 0.2 0.1" rpy="0 0 0"/>
      <geometry>
		<box size="0.1 0.1 0.4"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0.0 0.2 0.1" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="gripper_right_finger_joint" type="prismatic">
    <axis xyz="0 1 0"/>
    <origin rpy="0 0 0" xyz="0 0 0.475"/>
    <limit effort="1000.0" lower="0" upper="0.2" velocity="0.5"/>
    <parent link="palm"/>
    <child link="right_finger"/>
    <dynamics damping="10"/>
  </joint>

  <link name="right_finger">
    <collision>
      <origin xyz="0.0 -0.2 0.1" rpy="0 0 0"/>
      <geometry>
		<box size="0.1 0.1 0.4"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.0 -0.2 0.1" rpy="0 0 0"/>
      <geometry>
		<box size="0.1 0.1 0.4"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0.0 -0.2 0.1" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="revolute">
    <axis xyz="0 1 0" />
    <origin xyz="${camera_link * 2} 0 ${height1 - axel_offset*2}" rpy="0 0 0"/>
    <parent link="link1"/>
    <child link="camera_link"/>
	<limit effort="1000" velocity="2.0" lower="${-PI*1.25}" upper="${+PI*1.25}" />
    <dynamics damping="1"/>
  </joint>
  
  <!-- Camera      -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
  </link>
  
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="gripper_left_finger_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran5">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="gripper_right_finger_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor5">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran6">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="camera_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor6">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
